In [1]:
import numpy as np

# Vectors and Linear Equations

- Row picture of $Ax = b$
- Column picture of $Ax = b$


# The Idea of Elimination

1. 消元形成上三角矩阵，对角线上留下主元。
2. 反向消除解出方程。

主元不能为$0$，否则是无解（$0\neq0$）或者多解($0=0$)。

# Elimination Using Matrices

$$E = \begin{bmatrix}
1  & 0 & 0\\
-2 & 1 & 0 \\
0  & 0 & 1
\end{bmatrix}$$

In [2]:
A = np.array(
    [[ 2,  4, -2],
     [ 4,  9, -3],
     [-2, -3,  7]]
)

E = np.array(
    [[ 1,  0,  0],
     [-2,  1,  0],
     [ 0,  0,  1]]
)

print(E @ A)

[[ 2  4 -2]
 [ 0  1  1]
 [-2 -3  7]]


$$P = \begin{bmatrix}
0  & 1 & 0\\
1 & 0 & 0 \\
0  & 0 & 1
\end{bmatrix}$$

In [4]:
A = np.array(
    [[ 2,  4, -2],
     [ 4,  9, -3],
     [-2, -3,  7]]
)

E = np.array(
    [[ 0,  1,  0],
     [ 1,  0,  0],
     [ 0,  0,  1]]
)

print(E @ A)

[[ 4  9 -3]
 [ 2  4 -2]
 [-2 -3  7]]


# Inverse Matrix
$A$可逆：
- $A$所有主元不为零
- $\det{A} \neq 0$
- $Ax = b$只有一个解

$A$，$B$都可逆：
$$(AB)^{-1} = B^{-1}A^{-1}$$

Gauss-Jordan Elimination

三角阵的逆

Diagonally dominant matrices are invertible

# LU Factorization
$$ A = LU = LDU $$

# Transpose and Permutation
对称矩阵
$$A^T = A$$
$$A = LDU, A^T = U^TD^TL^T, D = D^T$$
$$A = LDL^T$$
点积
$$x \cdot y = x^Ty$$